DROP TABLE IF EXISTS note;

CREATE TABLE note
(
  id INTEGER
  AUTO_INCREMENT NOT NULL PRIMARY KEY,
category VARCHAR
  (2),
title VARCHAR
  (255),
memo VARCHAR
  (2000),
site_address VARCHAR
  (255),
created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
)DEFAULT CHARSET=utf8mb4;
