CREATE TABLE book_log (
id INTEGER AUTO_INCREMENT NOT NULL PRIMARY KEY,
book_title VARCHAR(255),
author VARCHAR(20),
status VARCHAR(3),
rating INTEGER,
comment VARCHAR(255),
created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP)
DEFAULT CHARSET=utf8mb4;
